language: latex

branches:
  only:
  - master

services:
  - docker

before_install:
  - docker pull noah95/latex
  - openssl aes-256-cbc -K $encrypted_4cf96262ec67_key -iv $encrypted_4cf96262ec67_iv -in deploy_rsa.enc -out /tmp/deploy_rsa -d


script:
  - cd template && make docker

addons:
  ssh_known_hosts: github.com

after_success:
  - eval "$(ssh-agent -s)"
  - chmod 600 /tmp/deploy_rsa
  - ssh-add /tmp/deploy_rsa
  - git remote add target git@github.com:noah95/formulasheets.git
  - git checkout -b build
  - git add -f */*.pdf
  - git status
  - git commit -am "Build"
  - git push target build --force

